# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_shrink_cpp')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_shrink_cpp')
    _shrink_cpp = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_shrink_cpp', [dirname(__file__)])
        except ImportError:
            import _shrink_cpp
            return _shrink_cpp
        try:
            _mod = imp.load_module('_shrink_cpp', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _shrink_cpp = swig_import_helper()
    del swig_import_helper
else:
    import _shrink_cpp
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _shrink_cpp.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _shrink_cpp.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _shrink_cpp.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _shrink_cpp.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _shrink_cpp.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _shrink_cpp.SwigPyIterator_equal(self, x)

    def copy(self):
        return _shrink_cpp.SwigPyIterator_copy(self)

    def next(self):
        return _shrink_cpp.SwigPyIterator_next(self)

    def __next__(self):
        return _shrink_cpp.SwigPyIterator___next__(self)

    def previous(self):
        return _shrink_cpp.SwigPyIterator_previous(self)

    def advance(self, n):
        return _shrink_cpp.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _shrink_cpp.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _shrink_cpp.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _shrink_cpp.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _shrink_cpp.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _shrink_cpp.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _shrink_cpp.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _shrink_cpp.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _shrink_cpp.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _shrink_cpp.VecInt___nonzero__(self)

    def __bool__(self):
        return _shrink_cpp.VecInt___bool__(self)

    def __len__(self):
        return _shrink_cpp.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _shrink_cpp.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _shrink_cpp.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _shrink_cpp.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _shrink_cpp.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _shrink_cpp.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _shrink_cpp.VecInt___setitem__(self, *args)

    def pop(self):
        return _shrink_cpp.VecInt_pop(self)

    def append(self, x):
        return _shrink_cpp.VecInt_append(self, x)

    def empty(self):
        return _shrink_cpp.VecInt_empty(self)

    def size(self):
        return _shrink_cpp.VecInt_size(self)

    def swap(self, v):
        return _shrink_cpp.VecInt_swap(self, v)

    def begin(self):
        return _shrink_cpp.VecInt_begin(self)

    def end(self):
        return _shrink_cpp.VecInt_end(self)

    def rbegin(self):
        return _shrink_cpp.VecInt_rbegin(self)

    def rend(self):
        return _shrink_cpp.VecInt_rend(self)

    def clear(self):
        return _shrink_cpp.VecInt_clear(self)

    def get_allocator(self):
        return _shrink_cpp.VecInt_get_allocator(self)

    def pop_back(self):
        return _shrink_cpp.VecInt_pop_back(self)

    def erase(self, *args):
        return _shrink_cpp.VecInt_erase(self, *args)

    def __init__(self, *args):
        this = _shrink_cpp.new_VecInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _shrink_cpp.VecInt_push_back(self, x)

    def front(self):
        return _shrink_cpp.VecInt_front(self)

    def back(self):
        return _shrink_cpp.VecInt_back(self)

    def assign(self, n, x):
        return _shrink_cpp.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _shrink_cpp.VecInt_resize(self, *args)

    def insert(self, *args):
        return _shrink_cpp.VecInt_insert(self, *args)

    def reserve(self, n):
        return _shrink_cpp.VecInt_reserve(self, n)

    def capacity(self):
        return _shrink_cpp.VecInt_capacity(self)
    __swig_destroy__ = _shrink_cpp.delete_VecInt
    __del__ = lambda self: None
VecInt_swigregister = _shrink_cpp.VecInt_swigregister
VecInt_swigregister(VecInt)

class VecFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _shrink_cpp.VecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _shrink_cpp.VecFloat___nonzero__(self)

    def __bool__(self):
        return _shrink_cpp.VecFloat___bool__(self)

    def __len__(self):
        return _shrink_cpp.VecFloat___len__(self)

    def __getslice__(self, i, j):
        return _shrink_cpp.VecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _shrink_cpp.VecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _shrink_cpp.VecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _shrink_cpp.VecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _shrink_cpp.VecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _shrink_cpp.VecFloat___setitem__(self, *args)

    def pop(self):
        return _shrink_cpp.VecFloat_pop(self)

    def append(self, x):
        return _shrink_cpp.VecFloat_append(self, x)

    def empty(self):
        return _shrink_cpp.VecFloat_empty(self)

    def size(self):
        return _shrink_cpp.VecFloat_size(self)

    def swap(self, v):
        return _shrink_cpp.VecFloat_swap(self, v)

    def begin(self):
        return _shrink_cpp.VecFloat_begin(self)

    def end(self):
        return _shrink_cpp.VecFloat_end(self)

    def rbegin(self):
        return _shrink_cpp.VecFloat_rbegin(self)

    def rend(self):
        return _shrink_cpp.VecFloat_rend(self)

    def clear(self):
        return _shrink_cpp.VecFloat_clear(self)

    def get_allocator(self):
        return _shrink_cpp.VecFloat_get_allocator(self)

    def pop_back(self):
        return _shrink_cpp.VecFloat_pop_back(self)

    def erase(self, *args):
        return _shrink_cpp.VecFloat_erase(self, *args)

    def __init__(self, *args):
        this = _shrink_cpp.new_VecFloat(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _shrink_cpp.VecFloat_push_back(self, x)

    def front(self):
        return _shrink_cpp.VecFloat_front(self)

    def back(self):
        return _shrink_cpp.VecFloat_back(self)

    def assign(self, n, x):
        return _shrink_cpp.VecFloat_assign(self, n, x)

    def resize(self, *args):
        return _shrink_cpp.VecFloat_resize(self, *args)

    def insert(self, *args):
        return _shrink_cpp.VecFloat_insert(self, *args)

    def reserve(self, n):
        return _shrink_cpp.VecFloat_reserve(self, n)

    def capacity(self):
        return _shrink_cpp.VecFloat_capacity(self)
    __swig_destroy__ = _shrink_cpp.delete_VecFloat
    __del__ = lambda self: None
VecFloat_swigregister = _shrink_cpp.VecFloat_swigregister
VecFloat_swigregister(VecFloat)

class VecVecFloat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecFloat, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _shrink_cpp.VecVecFloat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _shrink_cpp.VecVecFloat___nonzero__(self)

    def __bool__(self):
        return _shrink_cpp.VecVecFloat___bool__(self)

    def __len__(self):
        return _shrink_cpp.VecVecFloat___len__(self)

    def __getslice__(self, i, j):
        return _shrink_cpp.VecVecFloat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _shrink_cpp.VecVecFloat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _shrink_cpp.VecVecFloat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _shrink_cpp.VecVecFloat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _shrink_cpp.VecVecFloat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _shrink_cpp.VecVecFloat___setitem__(self, *args)

    def pop(self):
        return _shrink_cpp.VecVecFloat_pop(self)

    def append(self, x):
        return _shrink_cpp.VecVecFloat_append(self, x)

    def empty(self):
        return _shrink_cpp.VecVecFloat_empty(self)

    def size(self):
        return _shrink_cpp.VecVecFloat_size(self)

    def swap(self, v):
        return _shrink_cpp.VecVecFloat_swap(self, v)

    def begin(self):
        return _shrink_cpp.VecVecFloat_begin(self)

    def end(self):
        return _shrink_cpp.VecVecFloat_end(self)

    def rbegin(self):
        return _shrink_cpp.VecVecFloat_rbegin(self)

    def rend(self):
        return _shrink_cpp.VecVecFloat_rend(self)

    def clear(self):
        return _shrink_cpp.VecVecFloat_clear(self)

    def get_allocator(self):
        return _shrink_cpp.VecVecFloat_get_allocator(self)

    def pop_back(self):
        return _shrink_cpp.VecVecFloat_pop_back(self)

    def erase(self, *args):
        return _shrink_cpp.VecVecFloat_erase(self, *args)

    def __init__(self, *args):
        this = _shrink_cpp.new_VecVecFloat(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _shrink_cpp.VecVecFloat_push_back(self, x)

    def front(self):
        return _shrink_cpp.VecVecFloat_front(self)

    def back(self):
        return _shrink_cpp.VecVecFloat_back(self)

    def assign(self, n, x):
        return _shrink_cpp.VecVecFloat_assign(self, n, x)

    def resize(self, *args):
        return _shrink_cpp.VecVecFloat_resize(self, *args)

    def insert(self, *args):
        return _shrink_cpp.VecVecFloat_insert(self, *args)

    def reserve(self, n):
        return _shrink_cpp.VecVecFloat_reserve(self, n)

    def capacity(self):
        return _shrink_cpp.VecVecFloat_capacity(self)
    __swig_destroy__ = _shrink_cpp.delete_VecVecFloat
    __del__ = lambda self: None
VecVecFloat_swigregister = _shrink_cpp.VecVecFloat_swigregister
VecVecFloat_swigregister(VecVecFloat)

class VecVecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _shrink_cpp.VecVecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _shrink_cpp.VecVecInt___nonzero__(self)

    def __bool__(self):
        return _shrink_cpp.VecVecInt___bool__(self)

    def __len__(self):
        return _shrink_cpp.VecVecInt___len__(self)

    def __getslice__(self, i, j):
        return _shrink_cpp.VecVecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _shrink_cpp.VecVecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _shrink_cpp.VecVecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _shrink_cpp.VecVecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _shrink_cpp.VecVecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _shrink_cpp.VecVecInt___setitem__(self, *args)

    def pop(self):
        return _shrink_cpp.VecVecInt_pop(self)

    def append(self, x):
        return _shrink_cpp.VecVecInt_append(self, x)

    def empty(self):
        return _shrink_cpp.VecVecInt_empty(self)

    def size(self):
        return _shrink_cpp.VecVecInt_size(self)

    def swap(self, v):
        return _shrink_cpp.VecVecInt_swap(self, v)

    def begin(self):
        return _shrink_cpp.VecVecInt_begin(self)

    def end(self):
        return _shrink_cpp.VecVecInt_end(self)

    def rbegin(self):
        return _shrink_cpp.VecVecInt_rbegin(self)

    def rend(self):
        return _shrink_cpp.VecVecInt_rend(self)

    def clear(self):
        return _shrink_cpp.VecVecInt_clear(self)

    def get_allocator(self):
        return _shrink_cpp.VecVecInt_get_allocator(self)

    def pop_back(self):
        return _shrink_cpp.VecVecInt_pop_back(self)

    def erase(self, *args):
        return _shrink_cpp.VecVecInt_erase(self, *args)

    def __init__(self, *args):
        this = _shrink_cpp.new_VecVecInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _shrink_cpp.VecVecInt_push_back(self, x)

    def front(self):
        return _shrink_cpp.VecVecInt_front(self)

    def back(self):
        return _shrink_cpp.VecVecInt_back(self)

    def assign(self, n, x):
        return _shrink_cpp.VecVecInt_assign(self, n, x)

    def resize(self, *args):
        return _shrink_cpp.VecVecInt_resize(self, *args)

    def insert(self, *args):
        return _shrink_cpp.VecVecInt_insert(self, *args)

    def reserve(self, n):
        return _shrink_cpp.VecVecInt_reserve(self, n)

    def capacity(self):
        return _shrink_cpp.VecVecInt_capacity(self)
    __swig_destroy__ = _shrink_cpp.delete_VecVecInt
    __del__ = lambda self: None
VecVecInt_swigregister = _shrink_cpp.VecVecInt_swigregister
VecVecInt_swigregister(VecVecInt)


def partition(keys, nss, cnts):
    return _shrink_cpp.partition(keys, nss, cnts)
partition = _shrink_cpp.partition
# This file is compatible with both classic and new-style classes.


